name: janssencrm_backend
description: A new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^1.0.0
  mysql1: ^0.20.0
  intl: ^0.19.0
  bcrypt: ^1.1.3
  dart_jsonwebtoken: ^2.7.1
  excel: ^4.0.3

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.25.5
  very_good_analysis: ^5.1.0
